### ISSUE TITLE
Gender is missing from the dropdown options in the User Properties section

### ISSUE THREAD

**Issue by andromarces** [with-ours/ours-gtm-template#1]
Gender is missing from the dropdown options in the User Properties section:
![image](https://github.com/user-attachments/assets/0c5b6ce4-0a28-48e1-9e0e-a300eabf9b66)

**Comment by tylerzey** [comment]
Thanks!
https://github.com/with-ours/ours-gtm-template/commit/293751e4aadaca99d15f6fbe7dfe1dc37e3ef780
